FROM public.ecr.aws/lambda/python:3.11

ENV PIP_TRUSTED_HOST="pypi.org files.pythonhosted.org"

COPY api/requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir

COPY shared/ ${LAMBDA_TASK_ROOT}/shared/
COPY api/ ${LAMBDA_TASK_ROOT}/

CMD ["handler.handler"]
