FROM mcr.microsoft.com/playwright/python:v1.48.0-noble
WORKDIR /app

COPY aws/lambdas/scraper/requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir

COPY aws/lambdas/shared/ /app/shared/
COPY aws/lambdas/scraper/ /app/

ENV PYTHONPATH=/app:/app/shared

CMD ["python", "run.py"]
